"use client"

import { useEffect, useMemo, useState, type ComponentType } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { LoadingSpinner } from "@/components/ui/loading-spinner"
import { FileText, Download } from "lucide-react"
import { Document, Page, Text, View, usePDF } from "@react-pdf/renderer"

interface YearlyPDFReportGeneratorProps {
  yearData: any
  selectedYear: number | null
  templateNotes?: string
}

type YearlyReportDocumentComponent = ComponentType<{
  yearData: any
  year: number
  templateNotes?: string
}>

const EmptyDocument = () => (
  <Document>
    <Page>
      <View>
        <Text>Preparing report...</Text>
      </View>
    </Page>
  </Document>
)

export function YearlyPDFReportGenerator({ yearData, selectedYear, templateNotes = "" }: YearlyPDFReportGeneratorProps) {
  const [generating, setGenerating] = useState(false)
  const [DocumentComponent, setDocumentComponent] = useState<YearlyReportDocumentComponent | null>(null)
  const [loadError, setLoadError] = useState<string | null>(null)

  useEffect(() => {
    let isMounted = true
    import("@/components/admin/yearly-report-document")
      .then((mod) => {
        if (isMounted) {
          setDocumentComponent(() => mod.default)
        }
      })
      .catch((err) => {
        console.error("Failed to load PDF document component:", err)
        if (isMounted) {
          setLoadError("Unable to load PDF generator. Please refresh and try again.")
        }
      })
    return () => {
      isMounted = false
    }
  }, [])

  const documentElement = useMemo(() => {
    if (!DocumentComponent || !yearData || !selectedYear) return null
    return <DocumentComponent yearData={yearData} year={selectedYear} templateNotes={templateNotes} />
  }, [DocumentComponent, yearData, selectedYear, templateNotes])

  const [instance, updateInstance] = usePDF({
    document: documentElement || <EmptyDocument />,
  })

  useEffect(() => {
    if (documentElement) {
      updateInstance(documentElement)
    }
  }, [documentElement, updateInstance])

  const generatePDF = async () => {
    setGenerating(true)
    try {
      if (!documentElement) {
        throw new Error("Report data is not ready yet.")
      }
      // The PDF is already generated by usePDF hook
      if (instance.url) {
        const link = document.createElement("a")
        link.href = instance.url
        link.download = `yearly-report-${selectedYear}.pdf`
        link.click()
      }
    } catch (error) {
      console.error("Error generating PDF:", error)
    } finally {
      setGenerating(false)
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <FileText className="h-5 w-5" />
          Yearly PDF Report Generator
        </CardTitle>
        <CardDescription>
          Generate comprehensive PDF reports for the selected year
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="font-medium">Yearly Report</h3>
              <p className="text-sm text-gray-600">
                {selectedYear ? `Generate PDF report for ${selectedYear}` : "Select a year to generate report"}
              </p>
            </div>
            <Button 
              onClick={generatePDF} 
              disabled={
                generating || 
                !selectedYear || 
                !yearData || 
                !DocumentComponent || 
                !!loadError
              }
              className="flex items-center gap-2"
            >
              {generating ? (
                <LoadingSpinner size="sm" />
              ) : (
                <>
                  <Download className="h-4 w-4" />
                  Generate PDF
                </>
              )}
            </Button>
          </div>

          {instance.loading && (
            <div className="flex items-center justify-center py-4">
              <LoadingSpinner text="Generating PDF..." />
            </div>
          )}

          {loadError && (
            <div className="bg-red-50 border border-red-200 rounded-md p-4">
              <p className="text-sm text-red-700">
                {loadError}
              </p>
            </div>
          )}

          {instance.error && (
            <div className="bg-red-50 border border-red-200 rounded-md p-4">
              <p className="text-sm text-red-700">
                Error generating PDF: {typeof instance.error === 'string' ? instance.error : instance.error?.message || 'Unknown error'}
              </p>
            </div>
          )}

          {instance.url && (
            <div className="bg-green-50 border border-green-200 rounded-md p-4">
              <p className="text-sm text-green-700">
                PDF generated successfully! Click the button above to download.
              </p>
            </div>
          )}
        </div>
      </CardContent>
    </Card>
  )
}